환경기상 데이터 전처리
-------------------------------------------------------------------------------
> 1. 노원구/종로구로 저장된 데이터를 하나의 파일로 통합
> 2. 아웃라이어 제거

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import datetime
import glob
import os
directory = "./Desktop/dataset/bigcon/환경기상데이터/"

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
# 노트북 안에 그래프를 그리기 위해
%matplotlib inline

# 그래프에서 격자로 숫자 범위가 눈에 잘 띄도록 ggplot 스타일을 사용
plt.style.use('ggplot')

# 그래프에서 마이너스 폰트 깨지는 문제에 대한 대처
mpl.rcParams['axes.unicode_minus'] = False

데이터 불러오기
-------------------------------------------------------------------------------
>  노원구/종로구로 저장된 데이터를 하나의 파일로 통합하기 위하여 데이터를 불러와 concat하여줍니다.

In [2]:
pre_nowon = pd.read_csv('pre_nowon.csv')
pre_jongro = pd.read_csv('pre_jongro.csv')

In [3]:
pre_air = pd.concat([pre_nowon, pre_jongro])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [4]:
pre_air['Datetime'] = pre_air['Year'].astype('str') + pre_air['Month'].astype('str') + pre_air['Days'].astype('str')
f1 = lambda x: '%s/%02d/%02d'%(x[1], x[2], x[3])
pre_air['Datetime'] = pre_air['Datetime'].apply(lambda x: pd.to_datetime(str(x), format='%Y%m%d'))

In [5]:
pre_air
pre_air.to_csv('pre_air.csv', index = False)

In [6]:
pre_air

         Datetime  Days  Month  Year  hours  pm10  pm25    serial
0      2018-04-01     1      4  2018      0    33    16  11350595
1      2018-04-01     1      4  2018      1    38    17  11350595
2      2018-04-01     1      4  2018      2    42    20  11350595
3      2018-04-01     1      4  2018      3    31    16  11350595
4      2018-04-01     1      4  2018      4    30    16  11350595
5      2018-04-01     1      4  2018      5    36    19  11350595
6      2018-04-01     1      4  2018      6    43    23  11350595
7      2018-04-01     1      4  2018      7    39    20  11350595
8      2018-04-01     1      4  2018      8    58    30  11350595
9      2018-04-01     1      4  2018      9    61    28  11350595
10     2018-04-01     1      4  2018     10    61    24  11350595
11     2018-04-01     1      4  2018     11    63    24  11350595
12     2018-04-01     1      4  2018     12    57    22  11350595
13     2018-04-01     1      4  2018     13    45    17  11350595
14     2018-04-01     1      4  2018     14    43    18  11350595
15     2018-04-01     1      4  2018     15    45    22  11350595
16     2018-04-01     1      4  2018     16    64    33  11350595
17     2018-04-01     1      4  2018     17    66    36  11350595
18     2018-04-01     1      4  2018     18    66    37  11350595
19     2018-04-01     1      4  2018     19    63    36  11350595
20     2018-04-01     1      4  2018     20    66    35  11350595
21     2018-04-01     1      4  2018     21    72    36  11350595
22     2018-04-01     1      4  2018     22    74    35  11350595
23     2018-04-01     1      4  2018     23    69    32  11350595
24     2018-04-02     2      4  2018      0    68    31  11350595
25     2018-04-02     2      4  2018      1    66    28  11350595
26     2018-04-02     2      4  2018      2    63    25  11350595
27     2018-04-02     2      4  2018      3    63    24  11350595
28     2018-04-02     2      4  2018      4    63    25  11350595
29     2018-04-02     2      4  2018      5    59    24  11350595
...           ...   ...    ...   ...    ...   ...   ...       ...
112195 2019-03-30    30      3  2019     18    43    18  11110650
112196 2019-03-30    30      3  2019     19    39    21  11110650
112197 2019-03-30    30      3  2019     20    48    32  11110650
112198 2019-03-30    30      3  2019     21    48    34  11110650
112199 2019-03-30    30      3  2019     22    52    37  11110650
112200 2019-03-30    30      3  2019     23    44    33  11110650
112201 2019-03-31    31      3  2019      0    44    34  11110650
112202 2019-03-31    31      3  2019      1    41    33  11110650
112203 2019-03-31    31      3  2019      2    39    33  11110650
112204 2019-03-31    31      3  2019      3    40    30  11110650
112205 2019-03-31    31      3  2019      4    42    32  11110650
112206 2019-03-31    31      3  2019      5    42    34  11110650
112207 2019-03-31    31      3  2019      6    44    36  11110650
112208 2019-03-31    31      3  2019      7    53    43  11110650
112209 2019-03-31    31      3  2019      8    66    52  11110650
112210 2019-03-31    31      3  2019      9    61    42  11110650
112211 2019-03-31    31      3  2019     10    52    29  11110650
112212 2019-03-31    31      3  2019     11    60    31  11110650
112213 2019-03-31    31      3  2019     12    63    33  11110650
112214 2019-03-31    31      3  2019     13    54    29  11110650
112215 2019-03-31    31      3  2019     14    61    31  11110650
112216 2019-03-31    31      3  2019     15    61    30  11110650
112217 2019-03-31    31      3  2019     16    66    35  11110650
112218 2019-03-31    31      3  2019     17    57    29  11110650
112219 2019-03-31    31      3  2019     18    37    15  11110650
112220 2019-03-31    31      3  2019     19    32    15  11110650
112221 2019-03-31    31      3  2019     20    35    17  11110650
112222 2019-03-31    31      3  2019     21    36    16  11110650
112223 2019-03-31    31      3  2019     22    36    16  11110650
112224 2019-03-31    31      3  2019     23    31    18  11110650

[215846 rows x 8 columns]

아웃 라이어 제거
-------------------------------------------------------------------------------
>  환경기상데이터의 아웃라이어를 제거하기 위하여 'IsolationForest'를 사용합니다.

In [7]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.ensemble import IsolationForest

clf = IsolationForest(random_state=1)
clf.fit(pre_air[['pm25','pm10']])
y_pred_outliers = clf.predict(pre_air[['pm25','pm10']])

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:213: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:223: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:417: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)

In [8]:
out = pd.DataFrame(y_pred_outliers)
out = out.rename(columns={0: "out"})

In [9]:
out

        out
0         1
1         1
2         1
3         1
4         1
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
...     ...
215816    1
215817    1
215818    1
215819    1
215820    1
215821    1
215822    1
215823    1
215824    1
215825    1
215826    1
215827    1
215828    1
215829    1
215830    1
215831    1
215832    1
215833    1
215834    1
215835    1
215836    1
215837    1
215838    1
215839    1
215840    1
215841    1
215842    1
215843    1
215844    1
215845    1

[215846 rows x 1 columns]

In [10]:
pre_air = pre_air.reset_index(drop=True)
out = out.reset_index(drop=True)
pre_air_out = pd.merge(left=pre_air, right=out,left_index=True, right_index=True)

In [11]:
pre_air_out

         Datetime  Days  Month  Year  hours  pm10  pm25    serial  out
0      2018-04-01     1      4  2018      0    33    16  11350595    1
1      2018-04-01     1      4  2018      1    38    17  11350595    1
2      2018-04-01     1      4  2018      2    42    20  11350595    1
3      2018-04-01     1      4  2018      3    31    16  11350595    1
4      2018-04-01     1      4  2018      4    30    16  11350595    1
5      2018-04-01     1      4  2018      5    36    19  11350595    1
6      2018-04-01     1      4  2018      6    43    23  11350595    1
7      2018-04-01     1      4  2018      7    39    20  11350595    1
8      2018-04-01     1      4  2018      8    58    30  11350595    1
9      2018-04-01     1      4  2018      9    61    28  11350595    1
10     2018-04-01     1      4  2018     10    61    24  11350595    1
11     2018-04-01     1      4  2018     11    63    24  11350595    1
12     2018-04-01     1      4  2018     12    57    22  11350595    1
13     2018-04-01     1      4  2018     13    45    17  11350595    1
14     2018-04-01     1      4  2018     14    43    18  11350595    1
15     2018-04-01     1      4  2018     15    45    22  11350595    1
16     2018-04-01     1      4  2018     16    64    33  11350595    1
17     2018-04-01     1      4  2018     17    66    36  11350595    1
18     2018-04-01     1      4  2018     18    66    37  11350595    1
19     2018-04-01     1      4  2018     19    63    36  11350595    1
20     2018-04-01     1      4  2018     20    66    35  11350595    1
21     2018-04-01     1      4  2018     21    72    36  11350595    1
22     2018-04-01     1      4  2018     22    74    35  11350595    1
23     2018-04-01     1      4  2018     23    69    32  11350595    1
24     2018-04-02     2      4  2018      0    68    31  11350595    1
25     2018-04-02     2      4  2018      1    66    28  11350595    1
26     2018-04-02     2      4  2018      2    63    25  11350595    1
27     2018-04-02     2      4  2018      3    63    24  11350595    1
28     2018-04-02     2      4  2018      4    63    25  11350595    1
29     2018-04-02     2      4  2018      5    59    24  11350595    1
...           ...   ...    ...   ...    ...   ...   ...       ...  ...
215816 2019-03-30    30      3  2019     18    43    18  11110650    1
215817 2019-03-30    30      3  2019     19    39    21  11110650    1
215818 2019-03-30    30      3  2019     20    48    32  11110650    1
215819 2019-03-30    30      3  2019     21    48    34  11110650    1
215820 2019-03-30    30      3  2019     22    52    37  11110650    1
215821 2019-03-30    30      3  2019     23    44    33  11110650    1
215822 2019-03-31    31      3  2019      0    44    34  11110650    1
215823 2019-03-31    31      3  2019      1    41    33  11110650    1
215824 2019-03-31    31      3  2019      2    39    33  11110650    1
215825 2019-03-31    31      3  2019      3    40    30  11110650    1
215826 2019-03-31    31      3  2019      4    42    32  11110650    1
215827 2019-03-31    31      3  2019      5    42    34  11110650    1
215828 2019-03-31    31      3  2019      6    44    36  11110650    1
215829 2019-03-31    31      3  2019      7    53    43  11110650    1
215830 2019-03-31    31      3  2019      8    66    52  11110650    1
215831 2019-03-31    31      3  2019      9    61    42  11110650    1
215832 2019-03-31    31      3  2019     10    52    29  11110650    1
215833 2019-03-31    31      3  2019     11    60    31  11110650    1
215834 2019-03-31    31      3  2019     12    63    33  11110650    1
215835 2019-03-31    31      3  2019     13    54    29  11110650    1
215836 2019-03-31    31      3  2019     14    61    31  11110650    1
215837 2019-03-31    31      3  2019     15    61    30  11110650    1
215838 2019-03-31    31      3  2019     16    66    35  11110650    1
215839 2019-03-31    31      3  2019     17    57    29  11110650    1
215840 2019-03-31    31      3  2019     18    37    15  11110650    1
215841 2019-03-31    31      3  2019     19    32    15  11110650    1
215842 2019-03-31    31      3  2019     20    35    17  11110650    1
215843 2019-03-31    31      3  2019     21    36    16  11110650    1
215844 2019-03-31    31      3  2019     22    36    16  11110650    1
215845 2019-03-31    31      3  2019     23    31    18  11110650    1

[215846 rows x 9 columns]

In [12]:

pre_air_out = pre_air_out[pre_air_out.out != -1]
#race_an1.out
pre_air_out = pre_air_out.drop(['out'],axis=1)

pre_air_out.to_csv('./pre_air_out.csv',index=False)
print(pre_air_out.shape)

(194266, 8)

In [13]:
pre_air_out.to_csv('pre_air_out.csv', index = False)